#!/bin/sh

#set -x

CHECK_DIR=/tmp/OpenWRT_check
mkdir -pv $CHECK_DIR
cd $CHECK_DIR

baseurl=http://downloads.openwrt.org/snapshots/trunk/
platform=ar71xx
wget -nv -S $baseurl$platform/packages/Packages.gz -O Packages.gz
r=$(zgrep base-files_ Packages.gz | sed -e 's/^.*-r\(.*\)_ar71xx.ipk/\1/')
echo $r

RETVAL=$?
[ $RETVAL -eq 0 ] && echo $r > /vagrant/latest.txt
[ $RETVAL -ne 0 ] && echo Check Failed